"""
W13-D7: "Attention Is All You Need" Paper Review
==================================================
总结 Transformer 论文的核心内容。
"""


def print_separator(title):
    print("\n" + "=" * 60)
    print(f"  {title}")
    print("=" * 60)


def main():
    print_separator("Attention Is All You Need - 论文总结")
    print()
    print("论文信息:")
    print("  标题: Attention Is All You Need")
    print("  作者: Ashish Vaswani, Noam Shazeer, Niki Parmar,")
    print("        Jakob Uszkoreit, Llion Jones, Aidan N. Gomez,")
    print("        Lukasz Kaiser, Illia Polosukhin")
    print("  发表: NeurIPS 2017")
    print("  机构: Google Brain, Google Research, University of Toronto")
    print("  引用: 100,000+ (截至2025)")
    print()

    # ----------------------------------------------------------
    print_separator("1. 论文解决的核心问题")
    # ----------------------------------------------------------
    print()
    print("2017年之前的序列建模问题:")
    print()
    print("  RNN/LSTM:")
    print("    - 顺序计算: 无法并行，训练慢")
    print("    - 长距离依赖: 梯度消失/爆炸")
    print("    - 固定大小隐藏状态: 信息瓶颈")
    print()
    print("  CNN (如 ByteNet, ConvS2S):")
    print("    - 可以并行，但需要多层才能捕捉长距离关系")
    print("    - O(N) 层才能连接所有位置")
    print()
    print("  注意力机制 (Bahdanau, Luong):")
    print("    - 已用于 RNN 之上改善长距离依赖")
    print("    - 但仍然是附加组件，不是核心架构")
    print()
    print("  论文的核心洞察:")
    print("    '我们不需要 RNN，仅靠注意力机制就足够了!'")
    print()

    # ----------------------------------------------------------
    print_separator("2. 核心创新")
    # ----------------------------------------------------------
    print()
    print("创新 1: Scaled Dot-Product Attention")
    print("  Attention(Q,K,V) = softmax(QK^T / sqrt(d_k)) @ V")
    print("  - 去掉了 RNN 的顺序依赖")
    print("  - O(1) 步连接任意两个位置")
    print()
    print("创新 2: Multi-Head Attention")
    print("  - 多个头并行关注不同方面")
    print("  - 每个头学习不同的注意力模式")
    print("  - head_i = Attention(QW_q_i, KW_k_i, VW_v_i)")
    print("  - output = Concat(head_1,...,head_h) @ W_o")
    print()
    print("创新 3: 完全基于注意力的编码器-解码器")
    print("  Encoder: 堆叠 N 个自注意力层")
    print("  Decoder: 堆叠 N 个带掩码的自注意力 + 交叉注意力层")
    print("  - 没有任何 RNN 或 CNN")
    print("  - 高度并行化")
    print()
    print("创新 4: Positional Encoding")
    print("  - 用 sin/cos 函数编码位置信息")
    print("  - 不需要学习，可以外推到更长序列")
    print()
    print("创新 5: 三种注意力角色的区分")
    print("  - 编码器自注意力: 源序列内部关系")
    print("  - 解码器掩码自注意力: 目标序列内部关系 (因果)")
    print("  - 编码器-解码器注意力: 源和目标之间的对齐")
    print()

    # ----------------------------------------------------------
    print_separator("3. 架构细节")
    # ----------------------------------------------------------
    print()
    print("原始 Transformer (base):")
    print("  d_model = 512")
    print("  num_heads = 8")
    print("  d_ff = 2048")
    print("  num_layers = 6 (encoder) + 6 (decoder)")
    print("  参数量: ~65M")
    print()
    print("原始 Transformer (big):")
    print("  d_model = 1024")
    print("  num_heads = 16")
    print("  d_ff = 4096")
    print("  num_layers = 6 + 6")
    print("  参数量: ~213M")
    print()
    print("训练细节:")
    print("  优化器: Adam (beta1=0.9, beta2=0.98, eps=1e-9)")
    print("  学习率: warmup + inverse sqrt decay")
    print("  lr = d_model^(-0.5) * min(step^(-0.5), step * warmup^(-1.5))")
    print("  warmup_steps = 4000")
    print("  正则化: Dropout(0.1) + Label Smoothing(0.1)")
    print("  训练数据: WMT 2014 English-German (450万句对)")
    print("  训练时间: 8 P100 GPUs, 3.5 天 (base)")
    print()

    # ----------------------------------------------------------
    print_separator("4. 与前代架构对比")
    # ----------------------------------------------------------
    print()
    print(f"  {'模型':>20} | {'WMT EN-DE BLEU':>15} | {'训练成本':>12} | {'并行性':>10}")
    print(f"  {'-'*20}-+-{'-'*15}-+-{'-'*12}-+-{'-'*10}")
    print(f"  {'ByteNet':>20} | {'~23.0':>15} | {'中等':>12} | {'较好':>10}")
    print(f"  {'ConvS2S':>20} | {'25.16':>15} | {'中等':>12} | {'较好':>10}")
    print(f"  {'GNMT+RL (RNN)':>20} | {'24.61':>15} | {'高':>12} | {'差':>10}")
    print(f"  {'MoE':>20} | {'26.03':>15} | {'极高':>12} | {'差':>10}")
    print(f"  {'Transformer (base)':>20} | {'27.30':>15} | {'低':>12} | {'极好':>10}")
    print(f"  {'Transformer (big)':>20} | {'28.40':>15} | {'中等':>12} | {'极好':>10}")
    print()
    print("关键改进:")
    print("  1. BLEU 分数显著提升")
    print("  2. 训练成本大幅降低 (更少的 GPU 时间)")
    print("  3. 完全可并行化")
    print()

    # ----------------------------------------------------------
    print_separator("5. 论文的局限性")
    # ----------------------------------------------------------
    print()
    print("1. 计算复杂度:")
    print("   自注意力: O(n^2 * d)")
    print("   - 序列长度 n 增大时，计算量和内存平方增长")
    print("   - 长文档处理受限 (如书籍)")
    print()
    print("2. 位置编码:")
    print("   - sin/cos 编码是固定的，不是学习的")
    print("   - 外推到更长序列效果不好")
    print()
    print("3. 只验证了机器翻译任务:")
    print("   - 论文只在 WMT 翻译任务上做了实验")
    print("   - 其他 NLP 任务和 CV 领域的效果未知")
    print()
    print("4. 解码仍然串行:")
    print("   - 编码器可以并行，但解码器生成仍然需要自回归")
    print("   - 推理速度受限于序列长度")
    print()
    print("5. 缺乏归纳偏置 (inductive bias):")
    print("   - 不像 CNN 有局部性假设")
    print("   - 需要更多数据才能学好")
    print("   - 小数据集上可能不如 LSTM/CNN")
    print()

    # ----------------------------------------------------------
    print_separator("6. 现代改进方向")
    # ----------------------------------------------------------
    print()
    print("1. 高效注意力 (降低 O(n^2) 复杂度):")
    print("   - Linformer: 低秩近似, O(n)")
    print("   - Performer: 随机特征近似, O(n)")
    print("   - Flash Attention: IO 感知的精确注意力实现")
    print("   - Sparse Attention: 只计算部分注意力")
    print()
    print("2. 编码器-only 模型 (理解任务):")
    print("   - BERT (2018): 双向自注意力，MLM 预训练")
    print("   - 用于分类、NER、问答等")
    print()
    print("3. 解码器-only 模型 (生成任务):")
    print("   - GPT 系列 (2018-2023): 自回归语言模型")
    print("   - LLaMA, Mistral 等开源模型")
    print("   - ChatGPT, Claude 等对话模型")
    print()
    print("4. 编码器-解码器 模型 (序列到序列):")
    print("   - T5 (2019): Text-to-Text 统一框架")
    print("   - BART, mBART: 预训练的 seq2seq")
    print()
    print("5. 位置编码改进:")
    print("   - ALiBi: 线性偏置注意力")
    print("   - RoPE: 旋转位置编码 (LLaMA)")
    print()
    print("6. 架构改进:")
    print("   - Pre-LN (更稳定，GPT/BERT 使用)")
    print("   - RMSNorm (比 LayerNorm 更高效)")
    print("   - SwiGLU (替代 ReLU/GELU)")
    print("   - Multi-Query Attention / Grouped-Query Attention")
    print()
    print("7. 规模定律:")
    print("   - Scaling Laws (Kaplan et al., 2020):")
    print("     性能主要取决于模型大小、数据量和计算量")
    print("   - Chinchilla (2022): 数据量应与模型大小等比增长")
    print()

    # ----------------------------------------------------------
    print_separator("7. 影响力")
    # ----------------------------------------------------------
    print()
    print("Transformer 的影响远超 NLP:")
    print()
    print("  NLP:   BERT, GPT, T5, LLaMA, ChatGPT, Claude...")
    print("  CV:    Vision Transformer (ViT), DALL-E, Stable Diffusion...")
    print("  音频:  Whisper, Music Transformer...")
    print("  多模态: CLIP, GPT-4V, Gemini...")
    print("  科学:  AlphaFold 2 (蛋白质结构预测)")
    print("  RL:   Decision Transformer...")
    print()
    print("  'Attention Is All You Need' 可以说是 AI 领域")
    print("   过去十年最有影响力的论文之一。")
    print()

    print("=" * 60)
    print("  论文总结完毕")
    print("=" * 60)


if __name__ == "__main__":
    main()
